#!/bin/sh
# Copyright 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

base=$(dirname "$0")
python=python3
exec "${python}" "${base}/../build/gyp/gyp_main.py" "$@"
